name: metreflip
channels:
- conda-forge
dependencies:
- python=3.10
- pip
- pip:
  - wxPython; platform_system != "Windows"
  - psychopy==2023.2.3
  - psychtoolbox
  - pygame
  - pyparallel; platform_system != "Windows"
  - SoundFile; platform_system == "Windows"
  - websocket_client
  - sympy
  - mido
  - python-rtmidi
  - dataclass_csv
